export const questions = [
{
    id: "1",
    difficulty: "Easy",
    question: "What House Does Harry Potter Belong To?",
    answer_A: "Hufflepuff",
    answer_B: "Gryffindor",
    answer_C: "Slytherin",
    answer_D: "Ravenclaw",
    correct_answer: "B",
},
{
    id: "2",
    medium: "Medium",
    question: "What is Mr. Filchʻs Job at Hogwarts?",
    answer_A: "Janitor",
    answer_B: "Engineer",
    answer_C: "Housekeeper",
    answer_D: "Caretaker",
    correct_answer: "D",
},
{
    id: "3",
    difficulty: "Easy",
    question: "How are students put into their houses?",
    answer_A: "A Structured Quiz",
    answer_B: "A Choosing Spell",
    answer_C: "They receive a letter",
    answer_D: "The Sorting Hat",
    correct_answer: "D",
},
{
    id: "4",
    difficulty: "Easy",
    question: "What is Voldemortʻs full birth name?",
    answer_A: "Tom Marvolo Riddle",
    answer_B: "Tom Sectumsempra Riddle",
    answer_C: "Tom Riddle",
    answer_D: "Tom Lord Riddle",
    correct_answer: "A",
},
{
    id: "5",
    difficulty: "Medium",
    question: "Which word does NOT describe a wizard/witch with muggle parents?",
    answer_A: "Dirty-blood",
    answer_B: "Muggle-Born",
    answer_C: "Mudblood",
    answer_D: "Bleeder",
    correct_answer: "D",
},
{
    id: "6",
    difficulty: "Easy",
    question: "What Does The Marauderʻs Map Show?",
    answer_A: "Every protective spell around Hogwarts",
    answer_B: "The location of everyone at Hogwarts",
    answer_C: "A Map to the Marauderʻs Treasure",
    answer_D: "How to get past the Whomping Willow",
    correct_answer: "B",
},
{
    id: "7",
    difficulty: "Medium",
    question: "Which of the following people is NOT an animagus?",
    answer_A: "Remus Lupin",
    answer_B: "Victor Crum",
    answer_C: "Sirius Black",
    answer_D: "Proffesor McGonagall",
    correct_answer: "A",
},
{
    id: "8",
    difficulty: "Medium",
    question: "Why was the Whomping Willow planted?",
    answer_A: "To pay tribute to past heroes of the school",
    answer_B: "To protect Remus Lupin",
    answer_C: "To protect Sirius Black",
    answer_D: "To train students in Defense against the Dark Arts",
    correct_answer: "B",
},
]